### ISSUE TITLE
swift 3 - migration problems / tensorflow fyi

### ISSUE THREAD

**Issue by johndpope** [qoncept/TensorSwift#11]
<img width="1405" alt="screen shot 2017-05-29 at 2 59 06 pm" src="https://cloud.githubusercontent.com/assets/289994/26559770/9a5d8328-447f-11e7-82f8-ecd38f5c8213.png">

fyi - I'm getting close to having tensorflow via c_api in swift working.
could use some help though. I'm a bit of a newb when it comes to tensors.
checkout my branch - 
https://github.com/johndpope/tensorflow/tree/swift/tensorflow/swift

**Comment by t-ae** [comment]
Latest `master` branch and latest release `0.2.2` already fixed this problem.

**Comment by johndpope** [comment]
My bad, had an old fork.
