### ISSUE TITLE
How to export weights from Python?

### ISSUE THREAD

**Issue by ivanmkc** [qoncept/TensorSwift#2]
This is a pretty awesome project. I've trained some models on Tensorflow and want to export to the format you use loadFloatArray with. Any chance you can post some example Python code to export those weights? 

Thanks for building this btw!

**Comment by koher** [comment]
Hi. I did something like the following, though I'm not sure if it is the best way because I'm not so familiar with Python.

``` python
import struct

ndarray = W_conv1.eval(session=sess)
list = ndarray.reshape([-1]).tolist()
f = open("W_conv1", "wb")
f.write(struct.pack("%df" % len(list), *list))
f.close()
```

**Comment by ivanmkc** [comment]
Thanks, that looks easy enough. I'm going to try this out on the iPad and let you know how it goes.
