### ISSUE TITLE
fatal error: `elements.count` must be greater than or equal to `shape.volume`: elements.count = 1024, shape.volume = 3136:

### ISSUE THREAD

**Issue by LinShiwei** [qoncept/TensorSwift#3]
I have used my own images to trained by Tensorflow's DeepMnist example code. 
And I used the way you give in the other issue to output the Models.
But when I replace your Models with mine and run, I meet the error:

> fatal error: `elements.count` must be greater than or equal to `shape.volume`: elements.count = 1024, shape.volume = 3136:

I think maybe there is something wrong with my models.
But the DeepMnist training is successful:
![2016-07-13 10 26 21](https://cloud.githubusercontent.com/assets/15650591/16789953/5829cb70-48e4-11e6-89a5-a7756e6616dc.png)
And the output of models is successful, too.

What can I do to solve this problem? In order to replace the models successfully, should I do something with the `Classifier` Struct?

**Comment by koher** [comment]
I guess you have some mismatch of shapes between in Python and in Swift. Probably 3136 means 7 \* 7 \* 64. It is the input size of FC1 in "Deep MNIST for Experts".  But your tensor seems to have only 1024 elements.

**Comment by LinShiwei** [comment]
Do the models all convert in this way:

```
import struct

ndarray = W_conv1.eval(session=sess)
list = ndarray.reshape([-1]).tolist()
f = open("W_conv1", "wb")
f.write(struct.pack("%df" % len(list), *list))
f.close()
```

Only change the name 'W_conv1' to another?

**Comment by koher** [comment]
I guess you have something wrong about the shapes of the tensors. Could you show me both of your codes, in Python and in Swift?

**Comment by LinShiwei** [comment]
Deep mnist code I use is [here](https://github.com/LinShiwei/TensorflowLearning/blob/master/trainYourOwnMnist/lswDeepMnist.py).
I only train and test 36 images.
And my swift `classifier:` function:

``` swift
    private func classify(plate plate:UIImage,withNSValueArray array:NSMutableArray)->String{
        var result = ""
        for rectValue in array.reverse(){
            if rectValue is NSValue {
                let image = OpenCVWrapper.cutOutCharFrom(plate, withRectValue: rectValue as! NSValue)
                let grayImage = OpenCVWrapper.convertBGR2GRAY(image)
                let cgImage = grayImage.CGImage
                var pixels = [UInt8](count: inputSize * inputSize, repeatedValue: 0)

                let context  = CGBitmapContextCreate(&pixels, inputSize, inputSize, 8, inputSize, CGColorSpaceCreateDeviceGray()!, CGBitmapInfo.ByteOrderDefault.rawValue)!
                CGContextClearRect(context, CGRect(x: 0.0, y: 0.0, width: CGFloat(inputSize), height: CGFloat(inputSize)))

                let rect = CGRect(x: 0.0, y: 0.0, width: CGFloat(inputSize), height: CGFloat(inputSize))
                CGContextDrawImage(context, rect, cgImage)
                let input : Tensor

                input = Tensor(shape: [Dimension(inputSize), Dimension(inputSize), 1], elements: pixels.map { (Float($0) / 255.0 )})

                let resultInt = classifier.classify(input)
                result += String(resultInt)
            }

        }
        print("result is\(result)")
        return result
    }
```

Before I replace the models , it runs successfully , but the accuracy is not good enough. So I try to use my models but it doesn't work.

**Comment by koher** [comment]
Is the `classifier` identical to [this](https://github.com/qoncept/TensorSwift/blob/master/MNIST/Classifier.swift)? Then the `inputSize` must be 28. 

I guess the `inputSize` is 16 because you got the following error.

> fatal error: `elements.count` must be greater than or equal to `shape.volume`: elements.count = 1024, shape.volume = 3136:

16x16x1 -> 8x8x32 -> 4x4x64 = 1024

**Comment by LinShiwei** [comment]
I got it. How careless I am ! 

I changed the `inputSize` to `14` a week ago and forgot to change it back.

Thank you very much!

By the way, I find that no matter the `inputSize` is 14 or 16, the error message is the same as following.

> fatal error: `elements.count` must be greater than or equal to `shape.volume`: elements.count = 1024, shape.volume = 3136:

**Comment by koher** [comment]
👍

> By the way, I find that no matter the `inputSize` is 14 or 16, the error message is the same as following.

Because of 14x14x1 -> 7x7x32 -> 4x4x64 = 1024.
